# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0006_auto_20170724_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='degree_program',
            new_name='degree_Program',
        ),
    ]
