# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0007_auto_20170724_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profpic',
            field=models.CharField(default='def.png', max_length=1000),
        ),
    ]
