# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0008_user_profpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itempic',
            field=models.ImageField(default='true', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profpic',
            field=models.ImageField(default='def.png', upload_to=b''),
        ),
    ]
