# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0010_auto_20170724_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_field',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='profpic',
            field=models.ImageField(blank='true', height_field='height_field', null='true', upload_to=b'', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='user',
            name='width_field',
            field=models.IntegerField(),
        ),
    ]
