# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0012_auto_20170724_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='user',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='user',
            name='profpic',
            field=models.FileField(default='def.png', upload_to=b''),
        ),
    ]
