# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0013_auto_20170724_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profpic',
            field=models.FileField(default='/media/def.png', upload_to=b''),
        ),
    ]
