# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0015_auto_20170725_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itempic',
            field=models.FileField(default=True, null=True, upload_to=b''),
        ),
    ]
