# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0016_auto_20170725_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemtype',
            field=models.CharField(max_length=20),
        ),
    ]
