# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0018_auto_20170728_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemtag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
