# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20170724_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last',
            new_name='last_name',
        ),
    ]
