# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0011_auto_20170724_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itempic',
            field=models.ImageField(default=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profpic',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field'),
        ),
    ]
