# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0014_auto_20170724_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='item',
            name='itempic',
            field=models.ImageField(default=True, null=True, upload_to=b''),
        ),
    ]
